# Generated by Django 4.0.3 on 2022-07-05 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('intereses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=250)),
                ('requisitos', models.TextField(max_length=400)),
                ('video_vacante', models.URLField(blank=True, max_length=250, null=True)),
                ('sueldo', models.CharField(blank=True, max_length=100, null=True)),
                ('pregunta_1', models.CharField(blank=True, max_length=100, null=True)),
                ('pregunta_2', models.CharField(blank=True, max_length=100, null=True)),
                ('pregunta_3', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intereses.area')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.empresa')),
                ('jobrole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intereses.jobrole')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intereses.modalidad')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intereses.state')),
                ('tipo_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intereses.tipotrabajo')),
            ],
            options={
                'db_table': 'vacantes',
                'ordering': ['-updated_at'],
            },
        ),
    ]
