# Generated by Django 4.0.3 on 2022-07-07 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_nivelacademico_status_datosacademicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='datosAcademicos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.datosacademicos'),
        ),
    ]
