# Generated by Django 4.0.3 on 2022-07-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_persona_datosacademicos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosacademicos',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='datosAcademicos',
        ),
        migrations.AddField(
            model_name='persona',
            name='datosAcademicos',
            field=models.ManyToManyField(null=True, to='members.datosacademicos'),
        ),
    ]
