# Generated by Django 4.0.3 on 2022-07-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_datosacademicos_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosacademicos',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='persona',
            name='datosAcademicos',
            field=models.ManyToManyField(to='members.datosacademicos'),
        ),
    ]
