# Generated by Django 4.0.3 on 2022-07-09 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_datosacademicos_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='contact_email',
        ),
    ]
