# Generated by Django 4.0.3 on 2022-07-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_remove_persona_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='jobrole',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
